### ISSUE TITLE
Not work for PNPM

### ISSUE THREAD

**Issue by uinz** [uhyo/better-typescript-lib#20]
as title

**Comment by tksst** [comment]
This `.npmrc` works for me.

```
# better-typescript-lib installs the actual typing using dependencies and remaps it to @typescript/*.
public-hoist-pattern[]=@typescript/*
```

**Comment by uhyo** [comment]
@tksst Thank you for information! This seems to be an ideal solution.

This should be documented; I would be grateful it someone can help.
