### ISSUE TITLE
Add some clarity to the README

### ISSUE THREAD

**Issue by zaguiini** [uhyo/better-typescript-lib#23]
Hi, great project!

I think one way to make it even better would be some clarification on use cases.

I read through the document and the `JSON.parse` example is good but I think some code examples, use cases, and explanations on why installing the library is a good thing for the user's codebase would be beneficial in regards to adoption.

**Comment by uhyo** [comment]
Thank you for sthe uggestion! Yes definitely I should do that. I'll take time 🙂
