### ISSUE TITLE
Wrote a blog post about Better TypeScript Lib

### ISSUE THREAD

**Issue by aaditmshah** [uhyo/better-typescript-lib#29]
Here's the blog post. We can share it on social media to popularize this library.

https://medium.com/@aaditmshah.now/make-typescript-safe-again-47f60aad2f0a

On a side note, could you enable GitHub Discussions for this repository so that we can have longer discussions on topics that aren't necessarily issues?

**Comment by uhyo** [comment]
Wow, I'm so grateful for this 🥰 just shared on my Twitter.

Also Discussions is now enabled 🙂
