### ISSUE TITLE
NodeListOf#item should return TNode | null

### ISSUE THREAD

**Issue by Andyuu** [uhyo/better-typescript-lib#43]
Regarding this issue: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1268

Real return type: https://developer.mozilla.org/en-US/docs/Web/API/NodeList/item

It would be much better for item() in NodeListOf to match behaviour with at() for arrays. The small difference is that it can return null instead of undefined.

**Comment by uhyo** [comment]
Given that the linked issue says that it cannot be changed upstream because of backwards compabitility, I would love to accept this change.

**Comment by uhyo** [comment]
A fix has been released as `v2.8.0`. Thank you for reporting!
