### ISSUE TITLE
Array index signature to optional property

### ISSUE THREAD

**Issue by narumincho** [uhyo/better-typescript-lib#52]
```ts
const array: Array<string> = ["a", "aa", "aaa", "aaaa", "aaaaa"];

const handler: ProxyHandler<{ [index in number]: string }> = {
    get(target, prop, receiver) {
        return "a".repeat(Number.parseInt(prop.toString(), 10));
    },
};
const proxyObject: { [index in number]: string } = new Proxy({}, handler);
```

## compilerOptions.noUncheckedIndexedAccess: false (default)

```ts
const arrayResult = array[10]; // string
console.log(arrayResult); // undefined (Unexpected. this type is string but this value is undefined)

const proxyObjectResult = proxyObject[10]; // string
console.log(proxyObject[10]); // aaaaaaaaaa (Expected)
```

## compilerOptions.noUncheckedIndexedAccess: true

```ts
const arrayResult = array[10]; // string | undefined
console.log(arrayResult); // undefined (Expected)

const proxyObjectResult = proxyObject[10]; // string | undefined (Unexpected. Always expect to string)
console.log(proxyObject[10]); // aaaaaaaaaa
```

I propose the following changes

```diff
  interface Array<T> {
    ...
-  [n: number]: T;
+  [n in number]?: T;
  }
```

With this change, both types are expected if noUncheckedIndexedAccess is false

**Comment by uhyo** [comment]
Hello, thanks for the suggestion.

However, unfortunately I'm not willing to make this change given that `noUncheckedIndexedAccess` already covers this.

Approaching this problem from type definition side is imperfect. Also I don't like the idea of suggesting our users to turn off `noUncheckedIndexedAccess`.

**Comment by narumincho** [comment]
Thanks for your reply. When I tried to change `node_modules/@typescript/lib-es5/index.d.ts` directly, an error occurred, so it seems that this specification cannot be realized in the first place. 

![image](https://github.com/user-attachments/assets/c91e6f1f-a23f-4baf-b782-b4f914c9ca81)

Instead of rewriting the type definitions provided by TypeScript, I will implement it by creating and using another type definition. (https://github.com/narumincho/readonly)
