### ISSUE TITLE
Is there a list of changes from the standard lib.d.ts?

### ISSUE THREAD

**Issue by kasugaiasuka** [uhyo/better-typescript-lib#9]
I have a very strong interest in better-typescript-lib.
But I am hesitant to use this because I don't know what changes this will bring.

**Comment by uhyo** [comment]
Currently none, buT it is a very nice feature to have. 🥰  I'll work on this in the next holidays.

**Comment by uhyo** [comment]
Thank you for suggestion, now we have a diff file! :tada:

https://github.com/uhyo/better-typescript-lib/blob/master/docs/diff.md
